"""company - partita_iva, provincia, telefono, email, rimuovi zona e tax_id_estero

Revision ID: 04c9ab28c07a
Revises: df5593eed533
Create Date: 2026-07-03 15:42:48.027696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c9ab28c07a'
down_revision: Union[str, None] = 'df5593eed533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('partita_iva', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('provincia', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('telefono', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(), nullable=True))
    op.drop_constraint('companies_piva_key', 'companies', type_='unique')
    op.create_unique_constraint(None, 'companies', ['partita_iva'])
    op.drop_column('companies', 'zona')
    op.drop_column('companies', 'piva')
    op.drop_column('companies', 'tax_id_estero')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('tax_id_estero', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('piva', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('zona', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_unique_constraint('companies_piva_key', 'companies', ['piva'])
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'telefono')
    op.drop_column('companies', 'provincia')
    op.drop_column('companies', 'partita_iva')
    # ### end Alembic commands ###
