"""company_telefono_email_override

Revision ID: 0675f76ce03c
Revises: aa3d5299c1b5
Create Date: 2026-07-09 14:13:53.202328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0675f76ce03c'
down_revision: Union[str, None] = 'aa3d5299c1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('telefono_override', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('companies', sa.Column('email_override', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'email_override')
    op.drop_column('companies', 'telefono_override')
    # ### end Alembic commands ###
