"""radar_quantita_unita

Revision ID: 074fd576be4c
Revises: d5dbac4e498a
Create Date: 2026-07-14 14:34:51.151787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074fd576be4c'
down_revision: Union[str, None] = 'd5dbac4e498a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radar_segnalazioni', sa.Column('quantita', sa.Float(), nullable=True))
    op.add_column('radar_segnalazioni', sa.Column('unita', sa.String(), nullable=True))
    op.drop_constraint('radar_segnalazioni_contact_id_fkey', 'radar_segnalazioni', type_='foreignkey')
    op.drop_column('radar_segnalazioni', 'quantita_stimata')
    op.drop_column('radar_segnalazioni', 'contact_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radar_segnalazioni', sa.Column('contact_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('radar_segnalazioni', sa.Column('quantita_stimata', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('radar_segnalazioni_contact_id_fkey', 'radar_segnalazioni', 'contacts', ['contact_id'], ['id'])
    op.drop_column('radar_segnalazioni', 'unita')
    op.drop_column('radar_segnalazioni', 'quantita')
    # ### end Alembic commands ###
