"""notes_add_contact_id

Revision ID: 211e2845b30a
Revises: 7ee5de6b7c2c
Create Date: 2026-07-09 17:22:59.978950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211e2845b30a'
down_revision: Union[str, None] = '7ee5de6b7c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('contact_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notes', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'contact_id')
    # ### end Alembic commands ###
