"""reminder_add_mittente_email

Revision ID: 23405c82f7f4
Revises: 789e68a41cec
Create Date: 2026-07-10 17:13:39.647057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23405c82f7f4'
down_revision: Union[str, None] = '789e68a41cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_reminders', sa.Column('mittente_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_reminders', 'mittente_email')
    # ### end Alembic commands ###
