"""add_dedup_alerts

Revision ID: 414f24168861
Revises: e4d016148373
Create Date: 2026-07-14 16:05:33.109223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414f24168861'
down_revision: Union[str, None] = 'e4d016148373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_a_id', sa.UUID(), nullable=False),
    sa.Column('company_b_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('score_nome', sa.Float(), nullable=True),
    sa.Column('score_via', sa.Float(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_action', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_a_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_b_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dedup_alerts')
    # ### end Alembic commands ###
