"""add_created_by_to_companies

Revision ID: 5c5a0d4c91c6
Revises: 67efa7134efb
Create Date: 2026-07-15 11:01:57.301306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5a0d4c91c6'
down_revision: Union[str, None] = '67efa7134efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'created_by')
    # ### end Alembic commands ###
