"""add_created_by_to_contacts

Revision ID: 67efa7134efb
Revises: 5cd93bef94e4
Create Date: 2026-07-15 10:47:40.905390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67efa7134efb'
down_revision: Union[str, None] = '5cd93bef94e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'created_by')
    # ### end Alembic commands ###
