"""offer_line_item_descrizione_riga_codice_sap

Revision ID: 797d4766152d
Revises: 7b31b34296a4
Create Date: 2026-07-09 11:09:14.053892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797d4766152d'
down_revision: Union[str, None] = '7b31b34296a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_line_items', sa.Column('codice_sap', sa.String(), nullable=True))
    op.add_column('offer_line_items', sa.Column('descrizione_riga', sa.String(), nullable=True))
    op.alter_column('offer_line_items', 'prodotto_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer_line_items', 'prodotto_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('offer_line_items', 'descrizione_riga')
    op.drop_column('offer_line_items', 'codice_sap')
    # ### end Alembic commands ###
