"""opportunity_data_creazione_sap_creato_da

Revision ID: 7b31b34296a4
Revises: 4b4edab9f1a4
Create Date: 2026-07-08 17:24:59.057444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b31b34296a4'
down_revision: Union[str, None] = '4b4edab9f1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('data_creazione_sap', sa.Date(), nullable=True))
    op.add_column('opportunities', sa.Column('sap_creato_da', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'sap_creato_da')
    op.drop_column('opportunities', 'data_creazione_sap')
    # ### end Alembic commands ###
