"""add_updated_by_to_radar_segnalazioni

Revision ID: 8e50e68d2580
Revises: 5c5a0d4c91c6
Create Date: 2026-07-15 11:12:37.731191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e50e68d2580'
down_revision: Union[str, None] = '5c5a0d4c91c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radar_segnalazioni', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radar_segnalazioni', 'updated_by')
    # ### end Alembic commands ###
