"""add_import_logs

Revision ID: 9e39b20e52ff
Revises: ae081f5bbedb
Create Date: 2026-07-15 22:36:49.807570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e39b20e52ff'
down_revision: Union[str, None] = 'ae081f5bbedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('creati', sa.Integer(), nullable=False),
    sa.Column('aggiornati', sa.Integer(), nullable=False),
    sa.Column('saltati', sa.Integer(), nullable=False),
    sa.Column('dettaglio_saltati', sa.JSON(), nullable=False),
    sa.Column('created_ids', sa.JSON(), nullable=False),
    sa.Column('updated_snapshots', sa.JSON(), nullable=False),
    sa.Column('note_ids', sa.JSON(), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_logs')
    # ### end Alembic commands ###
