"""order_e_order_line_item

Revision ID: aa3d5299c1b5
Revises: f2e73c161f58
Create Date: 2026-07-09 11:32:40.875919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3d5299c1b5'
down_revision: Union[str, None] = 'f2e73c161f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('sap_document_id', sa.String(), nullable=True),
    sa.Column('valore_totale', sa.Numeric(), nullable=True),
    sa.Column('data_ordine', sa.Date(), nullable=True),
    sa.Column('data_creazione_sap', sa.Date(), nullable=True),
    sa.Column('sap_creato_da', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sap_document_id')
    )
    op.create_table('order_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('codice_sap', sa.String(), nullable=True),
    sa.Column('descrizione_riga', sa.String(), nullable=True),
    sa.Column('quantita', sa.Numeric(), nullable=True),
    sa.Column('unita_misura', sa.String(), nullable=True),
    sa.Column('prezzo_unitario', sa.Numeric(), nullable=True),
    sa.Column('totale_riga', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_line_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
