"""add_radar_tables

Revision ID: d5dbac4e498a
Revises: d965adda6eb4
Create Date: 2026-07-14 14:24:05.537265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5dbac4e498a'
down_revision: Union[str, None] = 'd965adda6eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radar_prodotti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['radar_prodotti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radar_segnalazioni',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prodotto_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('quantita_stimata', sa.String(), nullable=True),
    sa.Column('urgenza', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['agenti.id'], ),
    sa.ForeignKeyConstraint(['prodotto_id'], ['radar_prodotti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radar_segnalazioni')
    op.drop_table('radar_prodotti')
    # ### end Alembic commands ###
