"""contact_add_provenienza

Revision ID: d965adda6eb4
Revises: 23405c82f7f4
Create Date: 2026-07-14 13:14:57.036403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd965adda6eb4'
down_revision: Union[str, None] = '23405c82f7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('provenienza', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'provenienza')
    # ### end Alembic commands ###
