"""opportunity - aggiungo stage_changed_at rimuovo closed_at

Revision ID: df5593eed533
Revises: ee48e53786a9
Create Date: 2026-07-03 13:28:58.358985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df5593eed533'
down_revision: Union[str, None] = 'ee48e53786a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('stage_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('opportunities', 'closed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('opportunities', 'stage_changed_at')
    # ### end Alembic commands ###
