"""company_add_provenienza

Revision ID: e4d016148373
Revises: 074fd576be4c
Create Date: 2026-07-14 15:00:26.848050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d016148373'
down_revision: Union[str, None] = '074fd576be4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('provenienza', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'provenienza')
    # ### end Alembic commands ###
