"""blocco 2 - opportunity prodotto offer_line_item

Revision ID: ee48e53786a9
Revises: 8d3c15b0466c
Create Date: 2026-07-03 13:21:20.435166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee48e53786a9'
down_revision: Union[str, None] = '8d3c15b0466c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prodotti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codice_sap', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_sap')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('rep_id', sa.UUID(), nullable=True),
    sa.Column('agente_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('canale_acquisizione', sa.String(), nullable=True),
    sa.Column('sap_document_id', sa.String(), nullable=True),
    sa.Column('valore_totale', sa.Numeric(), nullable=True),
    sa.Column('data_scadenza', sa.Date(), nullable=True),
    sa.Column('dropout_reason', sa.String(), nullable=True),
    sa.Column('loss_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agente_id'], ['agenti.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sap_document_id')
    )
    op.create_table('offer_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('prodotto_id', sa.UUID(), nullable=False),
    sa.Column('quantita', sa.Numeric(), nullable=False),
    sa.Column('prezzo_unitario', sa.Numeric(), nullable=True),
    sa.Column('sconto', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['prodotto_id'], ['prodotti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_line_items')
    op.drop_table('opportunities')
    op.drop_table('prodotti')
    # ### end Alembic commands ###
