"""offer_line_item_totale_riga_unita_misura_rimuovi_prodotto_sconto

Revision ID: f2e73c161f58
Revises: 797d4766152d
Create Date: 2026-07-09 11:29:00.572031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e73c161f58'
down_revision: Union[str, None] = '797d4766152d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_line_items', sa.Column('unita_misura', sa.String(), nullable=True))
    op.add_column('offer_line_items', sa.Column('totale_riga', sa.Numeric(), nullable=True))
    op.alter_column('offer_line_items', 'quantita',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_constraint('offer_line_items_prodotto_id_fkey', 'offer_line_items', type_='foreignkey')
    op.drop_column('offer_line_items', 'sconto')
    op.drop_column('offer_line_items', 'prodotto_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_line_items', sa.Column('prodotto_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('offer_line_items', sa.Column('sconto', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_foreign_key('offer_line_items_prodotto_id_fkey', 'offer_line_items', 'prodotti', ['prodotto_id'], ['id'])
    op.alter_column('offer_line_items', 'quantita',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_column('offer_line_items', 'totale_riga')
    op.drop_column('offer_line_items', 'unita_misura')
    # ### end Alembic commands ###
